### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by zefj** [mpetazzoni/leaflet-gpx#87]
Hi, are there any plans for a release anytime soon? The version available on the npm registry does not support `gpx_options.joinTrackSegments`.

**Comment by mpetazzoni** [comment]
Done, 1.5.0 released.

**Comment by WuShell** [comment]
1.5.0 is not appearing on the github releases page:

https://github.com/mpetazzoni/leaflet-gpx/releases

Maybe you forgot to tag and push?

**Comment by mpetazzoni** [comment]
@WuShell My bad; done.

**Comment by WuShell** [comment]
> @WuShell My bad; done.

Great, thanks!
